# Generated by Django 5.2.1 on 2026-04-15 11:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_admin_notes_en_booking_admin_notes_sw_and_more'),
        ('consultations', '0002_consultationcategory_description_en_and_more'),
        ('payments', '0002_invoice_description_en_invoice_description_sw_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='paymenttransaction',
            name='payments_pa_flutter_a51359_idx',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='flutterwave_reference',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='flutterwave_request',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='flutterwave_response',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='gateway',
            field=models.CharField(choices=[('pawapay', 'PawaPay'), ('flutterwave', 'Flutterwave'), ('mpesa', 'M-Pesa Direct'), ('card', 'Credit/Debit Card'), ('bank', 'Bank Transfer')], default='pawapay', max_length=20),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='gateway_reference',
            field=models.CharField(blank=True, help_text='Reference from payment gateway', max_length=100),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='gateway_request',
            field=models.JSONField(blank=True, default=dict, help_text='Request sent to gateway'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='gateway_response',
            field=models.JSONField(blank=True, default=dict, help_text='Response from gateway'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_link',
            field=models.URLField(blank=True, help_text='Hosted payment link from gateway'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='webhook_response',
            field=models.JSONField(blank=True, default=dict, help_text='Webhook callback data'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['gateway_reference'], name='payments_pa_gateway_3df281_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['gateway'], name='payments_pa_gateway_e74888_idx'),
        ),
    ]
