# Generated by Django 5.2.1 on 2026-04-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcategory',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='description_sw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='name_sw',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='description_en',
            field=models.TextField(help_text='Full job description', null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='description_sw',
            field=models.TextField(help_text='Full job description', null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='location_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='location_sw',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='requirements_en',
            field=models.TextField(help_text='Job requirements and qualifications', null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='requirements_sw',
            field=models.TextField(help_text='Job requirements and qualifications', null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='responsibilities_en',
            field=models.TextField(help_text='Key responsibilities', null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='responsibilities_sw',
            field=models.TextField(help_text='Key responsibilities', null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='seo_description_en',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='seo_description_sw',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='seo_title_en',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='seo_title_sw',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='title_sw',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
