# Generated by Django 4.2.30 on 2026-07-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_jobcategory_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcategory',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='description_zh',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='name_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='name_zh',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='description_ar',
            field=models.TextField(help_text='Full job description', null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='description_fr',
            field=models.TextField(help_text='Full job description', null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='description_ru',
            field=models.TextField(help_text='Full job description', null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='description_zh',
            field=models.TextField(help_text='Full job description', null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='location_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='location_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='location_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='location_zh',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='requirements_ar',
            field=models.TextField(help_text='Job requirements and qualifications', null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='requirements_fr',
            field=models.TextField(help_text='Job requirements and qualifications', null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='requirements_ru',
            field=models.TextField(help_text='Job requirements and qualifications', null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='requirements_zh',
            field=models.TextField(help_text='Job requirements and qualifications', null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='responsibilities_ar',
            field=models.TextField(help_text='Key responsibilities', null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='responsibilities_fr',
            field=models.TextField(help_text='Key responsibilities', null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='responsibilities_ru',
            field=models.TextField(help_text='Key responsibilities', null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='responsibilities_zh',
            field=models.TextField(help_text='Key responsibilities', null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='seo_description_ar',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='seo_description_fr',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='seo_description_ru',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='seo_description_zh',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='seo_title_ar',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='seo_title_fr',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='seo_title_ru',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='seo_title_zh',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='title_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='title_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='title_zh',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
