# Generated by Django 5.2.1 on 2026-04-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='challenges_en',
            field=models.TextField(blank=True, help_text='Challenges faced during the project', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='challenges_sw',
            field=models.TextField(blank=True, help_text='Challenges faced during the project', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='client_name_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='client_name_sw',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_sw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_description_sw',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_title_sw',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='results_en',
            field=models.TextField(blank=True, help_text='Results and outcomes', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='results_sw',
            field=models.TextField(blank=True, help_text='Results and outcomes', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='solutions_en',
            field=models.TextField(blank=True, help_text='Solutions provided', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='solutions_sw',
            field=models.TextField(blank=True, help_text='Solutions provided', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='testimonial_author_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='testimonial_author_sw',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='testimonial_en',
            field=models.TextField(blank=True, help_text='Client testimonial for this project', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='testimonial_sw',
            field=models.TextField(blank=True, help_text='Client testimonial for this project', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_sw',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projectaward',
            name='award_name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projectaward',
            name='award_name_sw',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projectaward',
            name='awarding_body_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projectaward',
            name='awarding_body_sw',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projectaward',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectaward',
            name='description_sw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='description_sw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='name_sw',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='seo_description_en',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='seo_description_sw',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='seo_title_en',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='seo_title_sw',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
