# Generated by Django 4.2.30 on 2026-07-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_challenges_en_project_challenges_sw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='challenges_ar',
            field=models.TextField(blank=True, help_text='Challenges faced during the project', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='challenges_fr',
            field=models.TextField(blank=True, help_text='Challenges faced during the project', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='challenges_ru',
            field=models.TextField(blank=True, help_text='Challenges faced during the project', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='challenges_zh',
            field=models.TextField(blank=True, help_text='Challenges faced during the project', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='client_name_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='client_name_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='client_name_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='client_name_zh',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_zh',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_description_ar',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_description_fr',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_description_ru',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_description_zh',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_title_ar',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_title_fr',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_title_zh',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='results_ar',
            field=models.TextField(blank=True, help_text='Results and outcomes', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='results_fr',
            field=models.TextField(blank=True, help_text='Results and outcomes', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='results_ru',
            field=models.TextField(blank=True, help_text='Results and outcomes', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='results_zh',
            field=models.TextField(blank=True, help_text='Results and outcomes', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='solutions_ar',
            field=models.TextField(blank=True, help_text='Solutions provided', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='solutions_fr',
            field=models.TextField(blank=True, help_text='Solutions provided', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='solutions_ru',
            field=models.TextField(blank=True, help_text='Solutions provided', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='solutions_zh',
            field=models.TextField(blank=True, help_text='Solutions provided', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='testimonial_ar',
            field=models.TextField(blank=True, help_text='Client testimonial for this project', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='testimonial_author_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='testimonial_author_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='testimonial_author_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='testimonial_author_zh',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='testimonial_fr',
            field=models.TextField(blank=True, help_text='Client testimonial for this project', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='testimonial_ru',
            field=models.TextField(blank=True, help_text='Client testimonial for this project', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='testimonial_zh',
            field=models.TextField(blank=True, help_text='Client testimonial for this project', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_zh',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projectaward',
            name='award_name_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projectaward',
            name='award_name_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projectaward',
            name='award_name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projectaward',
            name='award_name_zh',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projectaward',
            name='awarding_body_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projectaward',
            name='awarding_body_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projectaward',
            name='awarding_body_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projectaward',
            name='awarding_body_zh',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projectaward',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectaward',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectaward',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectaward',
            name='description_zh',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='description_zh',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='name_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='name_zh',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='seo_description_ar',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='seo_description_fr',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='seo_description_ru',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='seo_description_zh',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='seo_title_ar',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='seo_title_fr',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='seo_title_ru',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='seo_title_zh',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
