# Generated by Django 4.2.30 on 2026-07-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_challenges_ar_project_challenges_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='work_status',
            field=models.CharField(choices=[('completed', 'Completed'), ('ongoing', 'On-going')], default='completed', help_text='Whether the work is finished or still on-going', max_length=10),
        ),
    ]
