# Generated by Django 5.2.1 on 2026-04-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='message_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='message_sw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='name_sw',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='description_sw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='name_sw',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='seo_description_en',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='seo_description_sw',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='seo_title_en',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='seo_title_sw',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='content_en',
            field=models.TextField(help_text='Full article content', null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='content_sw',
            field=models.TextField(help_text='Full article content', null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='excerpt_en',
            field=models.CharField(blank=True, help_text='Short summary for preview', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='excerpt_sw',
            field=models.CharField(blank=True, help_text='Short summary for preview', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='seo_description_en',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='seo_description_sw',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='seo_title_en',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='seo_title_sw',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='title_sw',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
