# Generated by Django 4.2.30 on 2026-07-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_comment_message_en_comment_message_sw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='message_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='message_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='message_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='message_zh',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='name_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='name_zh',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='description_zh',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='name_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='name_zh',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='seo_description_ar',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='seo_description_fr',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='seo_description_ru',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='seo_description_zh',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='seo_title_ar',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='seo_title_fr',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='seo_title_ru',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='seo_title_zh',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='content_ar',
            field=models.TextField(help_text='Full article content', null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='content_fr',
            field=models.TextField(help_text='Full article content', null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='content_ru',
            field=models.TextField(help_text='Full article content', null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='content_zh',
            field=models.TextField(help_text='Full article content', null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='excerpt_ar',
            field=models.CharField(blank=True, help_text='Short summary for preview', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='excerpt_fr',
            field=models.CharField(blank=True, help_text='Short summary for preview', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='excerpt_ru',
            field=models.CharField(blank=True, help_text='Short summary for preview', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='excerpt_zh',
            field=models.CharField(blank=True, help_text='Short summary for preview', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='seo_description_ar',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='seo_description_fr',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='seo_description_ru',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='seo_description_zh',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='seo_title_ar',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='seo_title_fr',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='seo_title_ru',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='seo_title_zh',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='title_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='title_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='title_zh',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
