# Generated by Django 4.2.30 on 2026-08-14 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_emailaccount_aliases'),
        ('core', '0002_workdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='related_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='notifications.incomingemail'),
        ),
        migrations.AddField(
            model_name='task',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To do'), ('in_progress', 'In progress'), ('submitted', 'Submitted for review'), ('returned', 'Returned for changes'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='todo', max_length=20),
        ),
    ]
