# Generated by Django 4.2.30 on 2026-08-14 23:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_calendarevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workdocument',
            name='is_shared',
        ),
        migrations.AddField(
            model_name='workdocument',
            name='shared_with',
            field=models.ManyToManyField(blank=True, help_text='Colleagues who can read this draft', related_name='shared_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
