# Generated by Django 4.2.30 on 2026-08-15 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_workdocument_is_shared_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='guests',
            field=models.CharField(blank=True, help_text='People without an account, e.g. "Mr Kileo, TANESCO"', max_length=500),
        ),
    ]
