# Generated by Django 4.2.30 on 2026-08-16 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0008_consultationrequest_progress_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_calendarevent_guests'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('kind', models.CharField(choices=[('checklist', 'Checklist / inspection'), ('measurements', 'Measurements'), ('risk', 'Risk assessment')], default='checklist', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('template_key', models.CharField(blank=True, max_length=60)),
                ('parameter', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('limit_value', models.FloatField(blank=True, null=True)),
                ('limit_source', models.CharField(blank=True, help_text='e.g. TBS / NEMC / WHO guideline', max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('collected_on', models.DateField(blank=True, null=True)),
                ('rows', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_sheets', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_sheets', to='consultations.consultationrequest')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_sheets', to='core.task')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('body', models.TextField()),
                ('is_internal', models.BooleanField(default=True, help_text='Internal notes are never shown to the client')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_notes', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_notes', to='consultations.consultationrequest')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_notes', to='core.task')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['job', 'created_at'], name='core_workno_job_id_5503e2_idx'), models.Index(fields=['task', 'created_at'], name='core_workno_task_id_45bdcf_idx')],
            },
        ),
    ]
