# Generated by Django 5.2.1 on 2026-04-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='description_sw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='name_sw',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teamachievement',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamachievement',
            name='description_sw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamachievement',
            name='issuer_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teamachievement',
            name='issuer_sw',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teamachievement',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teamachievement',
            name='title_sw',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_en',
            field=models.TextField(help_text='Professional biography', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_sw',
            field=models.TextField(help_text='Professional biography', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='certifications_en',
            field=models.JSONField(blank=True, default=list, help_text='List of certifications', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='certifications_sw',
            field=models.JSONField(blank=True, default=list, help_text='List of certifications', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='education_en',
            field=models.JSONField(blank=True, default=list, help_text='List of {degree, institution, year}', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='education_sw',
            field=models.JSONField(blank=True, default=list, help_text='List of {degree, institution, year}', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='expertise_areas_en',
            field=models.JSONField(blank=True, default=list, help_text='List of expertise areas', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='expertise_areas_sw',
            field=models.JSONField(blank=True, default=list, help_text='List of expertise areas', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='full_name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='full_name_sw',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_en',
            field=models.CharField(help_text='Job title e.g., Senior Consultant', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_sw',
            field=models.CharField(help_text='Job title e.g., Senior Consultant', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='work_experience_en',
            field=models.JSONField(blank=True, default=list, help_text='List of {position, company, years, description}', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='work_experience_sw',
            field=models.JSONField(blank=True, default=list, help_text='List of {position, company, years, description}', null=True),
        ),
        migrations.AddField(
            model_name='teamtestimonial',
            name='client_company_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teamtestimonial',
            name='client_company_sw',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teamtestimonial',
            name='client_name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teamtestimonial',
            name='client_name_sw',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teamtestimonial',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='teamtestimonial',
            name='content_sw',
            field=models.TextField(null=True),
        ),
    ]
