# Generated by Django 4.2.30 on 2026-07-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_department_description_en_department_description_sw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='description_zh',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='name_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='name_zh',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teamachievement',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamachievement',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamachievement',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamachievement',
            name='description_zh',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamachievement',
            name='issuer_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teamachievement',
            name='issuer_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teamachievement',
            name='issuer_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teamachievement',
            name='issuer_zh',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teamachievement',
            name='title_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teamachievement',
            name='title_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teamachievement',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teamachievement',
            name='title_zh',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_ar',
            field=models.TextField(help_text='Professional biography', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_fr',
            field=models.TextField(help_text='Professional biography', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_ru',
            field=models.TextField(help_text='Professional biography', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_zh',
            field=models.TextField(help_text='Professional biography', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='certifications_ar',
            field=models.JSONField(blank=True, default=list, help_text='List of certifications', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='certifications_fr',
            field=models.JSONField(blank=True, default=list, help_text='List of certifications', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='certifications_ru',
            field=models.JSONField(blank=True, default=list, help_text='List of certifications', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='certifications_zh',
            field=models.JSONField(blank=True, default=list, help_text='List of certifications', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='education_ar',
            field=models.JSONField(blank=True, default=list, help_text='List of {degree, institution, year}', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='education_fr',
            field=models.JSONField(blank=True, default=list, help_text='List of {degree, institution, year}', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='education_ru',
            field=models.JSONField(blank=True, default=list, help_text='List of {degree, institution, year}', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='education_zh',
            field=models.JSONField(blank=True, default=list, help_text='List of {degree, institution, year}', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='expertise_areas_ar',
            field=models.JSONField(blank=True, default=list, help_text='List of expertise areas', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='expertise_areas_fr',
            field=models.JSONField(blank=True, default=list, help_text='List of expertise areas', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='expertise_areas_ru',
            field=models.JSONField(blank=True, default=list, help_text='List of expertise areas', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='expertise_areas_zh',
            field=models.JSONField(blank=True, default=list, help_text='List of expertise areas', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='full_name_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='full_name_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='full_name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='full_name_zh',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_ar',
            field=models.CharField(help_text='Job title e.g., Senior Consultant', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_fr',
            field=models.CharField(help_text='Job title e.g., Senior Consultant', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_ru',
            field=models.CharField(help_text='Job title e.g., Senior Consultant', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_zh',
            field=models.CharField(help_text='Job title e.g., Senior Consultant', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='work_experience_ar',
            field=models.JSONField(blank=True, default=list, help_text='List of {position, company, years, description}', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='work_experience_fr',
            field=models.JSONField(blank=True, default=list, help_text='List of {position, company, years, description}', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='work_experience_ru',
            field=models.JSONField(blank=True, default=list, help_text='List of {position, company, years, description}', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='work_experience_zh',
            field=models.JSONField(blank=True, default=list, help_text='List of {position, company, years, description}', null=True),
        ),
        migrations.AddField(
            model_name='teamtestimonial',
            name='client_company_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teamtestimonial',
            name='client_company_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teamtestimonial',
            name='client_company_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teamtestimonial',
            name='client_company_zh',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teamtestimonial',
            name='client_name_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teamtestimonial',
            name='client_name_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teamtestimonial',
            name='client_name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teamtestimonial',
            name='client_name_zh',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teamtestimonial',
            name='content_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='teamtestimonial',
            name='content_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='teamtestimonial',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='teamtestimonial',
            name='content_zh',
            field=models.TextField(null=True),
        ),
    ]
