# Generated by Django 4.2.30 on 2026-07-03 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_consultationcategory_description_ar_and_more'),
        ('realtime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='related_consultation',
            field=models.ForeignKey(blank=True, help_text='Optional link giving a client-staff conversation its context', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='consultations.consultationrequest'),
        ),
    ]
