# Generated by Django 5.2.1 on 2026-04-21 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_emailverificationtoken_token_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['priority_level', 'name'], 'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='auth_user_role_id_d00849_idx',
            old_name='auth_user_role_f90fd2_idx',
        ),
        migrations.AlterField(
            model_name='role',
            name='is_system_role',
            field=models.BooleanField(default=False, help_text='System roles cannot be deleted'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.role'),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
