# Generated by Django 5.2.1 on 2026-04-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationcategory',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationcategory',
            name='description_sw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationcategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='consultationcategory',
            name='name_sw',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='consultationcategory',
            name='seo_description_en',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='consultationcategory',
            name='seo_description_sw',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='consultationcategory',
            name='seo_title_en',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='consultationcategory',
            name='seo_title_sw',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='consultationservice',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='consultationservice',
            name='description_sw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='consultationservice',
            name='faq_en',
            field=models.JSONField(blank=True, default=list, help_text='List of {question, answer}', null=True),
        ),
        migrations.AddField(
            model_name='consultationservice',
            name='faq_sw',
            field=models.JSONField(blank=True, default=list, help_text='List of {question, answer}', null=True),
        ),
        migrations.AddField(
            model_name='consultationservice',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='consultationservice',
            name='name_sw',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='consultationservice',
            name='prerequisites_en',
            field=models.JSONField(blank=True, default=list, help_text='List of prerequisites', null=True),
        ),
        migrations.AddField(
            model_name='consultationservice',
            name='prerequisites_sw',
            field=models.JSONField(blank=True, default=list, help_text='List of prerequisites', null=True),
        ),
    ]
