# Generated by Django 4.2.30 on 2026-04-27 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultations', '0002_consultationcategory_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='services/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service Image',
                'verbose_name_plural': 'Service Images (Gallery)',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='consultationcategory',
            options={'ordering': ['level', 'order', 'name'], 'verbose_name_plural': 'Consultation Categories'},
        ),
        migrations.RemoveIndex(
            model_name='consultationrequest',
            name='consultatio_status_4036b0_idx',
        ),
        migrations.AddField(
            model_name='consultationcategory',
            name='level',
            field=models.IntegerField(default=0, editable=False, help_text='0=Main, 1=Sub, 2=Sub-Sub'),
        ),
        migrations.AddField(
            model_name='consultationcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='consultations.consultationcategory'),
        ),
        migrations.AddField(
            model_name='consultationdocument',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultationdocument',
            name='document_type',
            field=models.CharField(choices=[('proposal', 'Proposal'), ('contract', 'Contract'), ('report', 'Report'), ('invoice', 'Invoice'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='consultationdocument',
            name='file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationfollowup',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationfollowup',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='alternative_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='client_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='client_rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='preferred_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='consultationservice',
            name='benefits',
            field=models.JSONField(blank=True, default=list, help_text='List of benefit strings'),
        ),
        migrations.AddField(
            model_name='consultationservice',
            name='currency',
            field=models.CharField(default='TZS', max_length=3),
        ),
        migrations.AddField(
            model_name='consultationservice',
            name='deliverables',
            field=models.JSONField(blank=True, default=list, help_text='List of deliverable strings'),
        ),
        migrations.AddField(
            model_name='consultationservice',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji or SVG icon', max_length=100),
        ),
        migrations.AddField(
            model_name='consultationservice',
            name='image',
            field=models.ImageField(blank=True, help_text='Main service image (thumbnail/primary)', null=True, upload_to='services/'),
        ),
        migrations.AddField(
            model_name='consultationservice',
            name='max_clients',
            field=models.IntegerField(default=1, help_text='Maximum clients per session'),
        ),
        migrations.AddField(
            model_name='consultationservice',
            name='price_range_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='consultationservice',
            name='price_range_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='consultationservice',
            name='price_type',
            field=models.CharField(choices=[('fixed', 'Fixed Price'), ('hourly', 'Per Hour'), ('range', 'Price Range'), ('quote', 'Get Quote')], default='fixed', max_length=20),
        ),
        migrations.AddField(
            model_name='consultationservice',
            name='seo_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='consultationservice',
            name='seo_title',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='consultationcategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji or SVG icon', max_length=100),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='consultationservice',
            name='prerequisites',
            field=models.JSONField(blank=True, default=list, help_text='List of prerequisite strings'),
        ),
        migrations.AlterField(
            model_name='consultationservice',
            name='prerequisites_en',
            field=models.JSONField(blank=True, default=list, help_text='List of prerequisite strings', null=True),
        ),
        migrations.AlterField(
            model_name='consultationservice',
            name='prerequisites_sw',
            field=models.JSONField(blank=True, default=list, help_text='List of prerequisite strings', null=True),
        ),
        migrations.AddIndex(
            model_name='consultationcategory',
            index=models.Index(fields=['is_active', 'level', 'order'], name='consultatio_is_acti_56d94f_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationcategory',
            index=models.Index(fields=['parent', 'is_active'], name='consultatio_parent__9b49d4_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationcategory',
            index=models.Index(fields=['slug'], name='consultatio_slug_0d44fa_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationcategory',
            index=models.Index(fields=['level'], name='consultatio_level_7eedc8_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationrequest',
            index=models.Index(fields=['status', '-created_at'], name='consultatio_status_ba6ccb_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationrequest',
            index=models.Index(fields=['priority', 'status'], name='consultatio_priorit_0eb098_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationservice',
            index=models.Index(fields=['is_active', 'order'], name='consultatio_is_acti_795aa3_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationservice',
            index=models.Index(fields=['category', 'is_active'], name='consultatio_categor_485e5b_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationservice',
            index=models.Index(fields=['is_featured', 'is_active'], name='consultatio_is_feat_1a5131_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationservice',
            index=models.Index(fields=['slug'], name='consultatio_slug_2c15ae_idx'),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='consultations.consultationservice'),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='serviceimage',
            index=models.Index(fields=['service', 'is_active', 'order'], name='consultatio_service_f489cc_idx'),
        ),
    ]
