# Generated by Django 4.2.30 on 2026-04-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_serviceimage_alter_consultationcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationcategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji or text icon', max_length=500),
        ),
        migrations.AlterField(
            model_name='consultationcategory',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='consultationcategory',
            name='name_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='consultationcategory',
            name='name_sw',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='consultationcategory',
            name='seo_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='consultationcategory',
            name='seo_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultationcategory',
            name='seo_description_sw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultationcategory',
            name='seo_title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='consultationcategory',
            name='seo_title_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultationcategory',
            name='seo_title_sw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultationcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='consultationdocument',
            name='document_type',
            field=models.CharField(choices=[('proposal', 'Proposal'), ('contract', 'Contract'), ('report', 'Report'), ('invoice', 'Invoice'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='consultationdocument',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='consultationfollowup',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='budget_range',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=50),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='consultationservice',
            name='currency',
            field=models.CharField(default='TZS', max_length=10),
        ),
        migrations.AlterField(
            model_name='consultationservice',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji or text icon', max_length=500),
        ),
        migrations.AlterField(
            model_name='consultationservice',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='consultationservice',
            name='name_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='consultationservice',
            name='name_sw',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='consultationservice',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='consultationservice',
            name='price_range_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='consultationservice',
            name='price_range_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='consultationservice',
            name='price_type',
            field=models.CharField(choices=[('fixed', 'Fixed Price'), ('hourly', 'Per Hour'), ('range', 'Price Range'), ('quote', 'Get Quote')], default='fixed', max_length=50),
        ),
        migrations.AlterField(
            model_name='consultationservice',
            name='seo_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='consultationservice',
            name='seo_title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='consultationservice',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=500),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='caption',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
