# Generated by Django 4.2.30 on 2026-07-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_alter_consultationcategory_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationcategory',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationcategory',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationcategory',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationcategory',
            name='description_zh',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationcategory',
            name='name_ar',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='consultationcategory',
            name='name_fr',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='consultationcategory',
            name='name_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='consultationcategory',
            name='name_zh',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='consultationcategory',
            name='seo_description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationcategory',
            name='seo_description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationcategory',
            name='seo_description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationcategory',
            name='seo_description_zh',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationcategory',
            name='seo_title_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationcategory',
            name='seo_title_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationcategory',
            name='seo_title_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationcategory',
            name='seo_title_zh',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationservice',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='consultationservice',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='consultationservice',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='consultationservice',
            name='description_zh',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='consultationservice',
            name='faq_ar',
            field=models.JSONField(blank=True, default=list, help_text='List of {question, answer}', null=True),
        ),
        migrations.AddField(
            model_name='consultationservice',
            name='faq_fr',
            field=models.JSONField(blank=True, default=list, help_text='List of {question, answer}', null=True),
        ),
        migrations.AddField(
            model_name='consultationservice',
            name='faq_ru',
            field=models.JSONField(blank=True, default=list, help_text='List of {question, answer}', null=True),
        ),
        migrations.AddField(
            model_name='consultationservice',
            name='faq_zh',
            field=models.JSONField(blank=True, default=list, help_text='List of {question, answer}', null=True),
        ),
        migrations.AddField(
            model_name='consultationservice',
            name='name_ar',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='consultationservice',
            name='name_fr',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='consultationservice',
            name='name_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='consultationservice',
            name='name_zh',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='consultationservice',
            name='prerequisites_ar',
            field=models.JSONField(blank=True, default=list, help_text='List of prerequisite strings', null=True),
        ),
        migrations.AddField(
            model_name='consultationservice',
            name='prerequisites_fr',
            field=models.JSONField(blank=True, default=list, help_text='List of prerequisite strings', null=True),
        ),
        migrations.AddField(
            model_name='consultationservice',
            name='prerequisites_ru',
            field=models.JSONField(blank=True, default=list, help_text='List of prerequisite strings', null=True),
        ),
        migrations.AddField(
            model_name='consultationservice',
            name='prerequisites_zh',
            field=models.JSONField(blank=True, default=list, help_text='List of prerequisite strings', null=True),
        ),
    ]
