# Generated by Django 4.2.30 on 2026-08-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_consultationcategory_description_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationdocument',
            name='is_deliverable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
    ]
