# Generated by Django 4.2.30 on 2026-08-08 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0006_consultationdocument_is_deliverable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='consultations.consultationcategory'),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='consultations.consultationservice'),
        ),
    ]
