# Generated by Django 4.2.30 on 2026-08-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0007_consultationrequest_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, help_text='0-100'),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('submitted', 'Submitted for review'), ('returned', 'Returned for changes'), ('completed', 'Completed'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
    ]
