# Generated by Django 5.2.1 on 2026-04-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='description_sw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='mission_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='mission_sw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='title_en',
            field=models.CharField(default='About Us', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='title_sw',
            field=models.CharField(default='About Us', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='vision_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='vision_sw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_sw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_sw',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='cta_second_text_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='cta_second_text_sw',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='cta_text_en',
            field=models.CharField(default='Get Started', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='cta_text_sw',
            field=models.CharField(default='Get Started', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='subtitle_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='subtitle_sw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title_sw',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_sw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='name_sw',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seodata',
            name='keywords_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='seodata',
            name='keywords_sw',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='seodata',
            name='meta_description_en',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='seodata',
            name='meta_description_sw',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='seodata',
            name='meta_title_en',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='seodata',
            name='meta_title_sw',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='servicehighlight',
            name='badge_text_en',
            field=models.CharField(blank=True, help_text='e.g., Popular, New, Best Seller', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicehighlight',
            name='badge_text_sw',
            field=models.CharField(blank=True, help_text='e.g., Popular, New, Best Seller', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicehighlight',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='servicehighlight',
            name='description_sw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='servicehighlight',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='servicehighlight',
            name='title_sw',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_about_text_en',
            field=models.TextField(blank=True, help_text='About text in footer', null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_about_text_sw',
            field=models.TextField(blank=True, help_text='About text in footer', null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_copyright_text_en',
            field=models.CharField(default='© 2025 Fee-Vert Solution Limited. All rights reserved.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_copyright_text_sw',
            field=models.CharField(default='© 2025 Fee-Vert Solution Limited. All rights reserved.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_name_en',
            field=models.CharField(default='Fee-Vert Solution Limited', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_name_sw',
            field=models.CharField(default='Fee-Vert Solution Limited', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_tagline_en',
            field=models.CharField(blank=True, help_text='Short slogan or tagline', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_tagline_sw',
            field=models.CharField(blank=True, help_text='Short slogan or tagline', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='client_company_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='client_company_sw',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='client_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='client_name_sw',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='client_role_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='client_role_sw',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='content_sw',
            field=models.TextField(null=True),
        ),
    ]
