# Generated by Django 4.2.30 on 2026-04-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_aboutsection_description_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutsection',
            options={'verbose_name': 'About Section', 'verbose_name_plural': 'About Sections'},
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='core_values',
            field=models.JSONField(blank=True, default=list, help_text="List of {icon, title, description}. Example: [{'icon': '💎', 'title': 'Integrity', 'description': '...'}]"),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='stats',
            field=models.JSONField(blank=True, default=list, help_text="List of {number, label}. Example: [{'number': '50', 'label': 'Projects Completed'}]"),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='why_choose_us',
            field=models.JSONField(blank=True, default=list, help_text="List of {icon, title, description}. Example: [{'icon': '🎓', 'title': 'Expert Team', 'description': '...'}]"),
        ),
    ]
