# Generated by Django 4.2.30 on 2026-04-30 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_alter_aboutsection_options_aboutsection_core_values_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='core_values',
            field=models.JSONField(blank=True, default=list, help_text="List of {icon, title, description, image}. Example: [{'icon': '💎', 'title': 'Integrity', 'description': '...', 'image': 'cloudinary_url'}]"),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='stats',
            field=models.JSONField(blank=True, default=list, help_text="List of {number, label, icon}. Example: [{'number': '50', 'label': 'Projects Completed'}]"),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='why_choose_us',
            field=models.JSONField(blank=True, default=list, help_text="List of {icon, title, description, image}. Example: [{'icon': '🎓', 'title': 'Expert Team', 'description': '...', 'image': 'cloudinary_url'}]"),
        ),
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='about/gallery/')),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('section', models.CharField(choices=[('core_values', 'Core Values'), ('why_choose_us', 'Why Choose Us'), ('general', 'General'), ('stats', 'Statistics')], default='general', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='home.aboutsection')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'About Image',
                'verbose_name_plural': 'About Images (Gallery)',
                'ordering': ['section', 'order', '-created_at'],
                'indexes': [models.Index(fields=['about', 'section', 'is_active'], name='home_abouti_about_i_548334_idx')],
            },
        ),
    ]
