# Generated by Django 4.2.30 on 2026-05-07 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_alter_aboutsection_core_values_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=300)),
                ('job_title', models.CharField(blank=True, max_length=200)),
                ('contact_type', models.CharField(choices=[('lead', 'Lead'), ('client', 'Client'), ('vendor', 'Vendor'), ('partner', 'Partner'), ('supplier', 'Supplier'), ('other', 'Other')], default='lead', max_length=50)),
                ('primary_email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('secondary_emails', models.JSONField(blank=True, default=list)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('alternate_phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('region', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(default='Tanzania', max_length=200)),
                ('source', models.CharField(blank=True, help_text='How did they find us?', max_length=200)),
                ('source_channel', models.CharField(blank=True, choices=[('contact_form', 'Contact Form'), ('email', 'Email'), ('consultation', 'Consultation'), ('booking', 'Booking'), ('referral', 'Referral'), ('social', 'Social Media'), ('other', 'Other')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('total_messages', models.IntegerField(default=0)),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('first_contacted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Unified Inbox', 'verbose_name_plural': 'Unified Inbox (All Messages)'},
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='cc_emails',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='channel',
            field=models.CharField(choices=[('contact_form', 'Contact Form'), ('email', 'Email'), ('sms', 'SMS'), ('consultation', 'Consultation'), ('booking', 'Booking'), ('chat', 'Live Chat'), ('internal', 'Internal Note')], db_index=True, default='contact_form', max_length=50),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='headers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='in_reply_to',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_incoming',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='message_id',
            field=models.CharField(blank=True, db_index=True, max_length=500),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=50),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='sla_breached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='sla_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('in_progress', 'In Progress'), ('responded', 'Responded'), ('resolved', 'Resolved'), ('spam', 'Spam'), ('archived', 'Archived')], db_index=True, default='unread', max_length=50),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='thread_id',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='core_values',
            field=models.JSONField(blank=True, default=list, help_text='List of {icon, title, description, image}'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='stats',
            field=models.JSONField(blank=True, default=list, help_text='List of {number, label, icon}'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='why_choose_us',
            field=models.JSONField(blank=True, default=list, help_text='List of {icon, title, description, image}'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='footer_copyright_text',
            field=models.CharField(default='(c) 2025 Fee-Vert Solution Limited. All rights reserved.', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='footer_copyright_text_en',
            field=models.CharField(default='(c) 2025 Fee-Vert Solution Limited. All rights reserved.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='footer_copyright_text_sw',
            field=models.CharField(default='(c) 2025 Fee-Vert Solution Limited. All rights reserved.', max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['channel', 'status'], name='home_contac_channel_e21c1e_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['assigned_to', 'status'], name='home_contac_assigne_ae117e_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['priority', '-created_at'], name='home_contac_priorit_fe00a5_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['message_id'], name='home_contac_message_5b4565_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['thread_id'], name='home_contac_thread__2d2a4b_idx'),
        ),
        migrations.AddField(
            model_name='contact',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contact',
            name='linked_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contact',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='home.contact'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['primary_email'], name='home_contac_primary_d51724_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['contact_type'], name='home_contac_contact_2ee2a1_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['phone'], name='home_contac_phone_9bc79e_idx'),
        ),
    ]
