# Generated by Django 4.2.30 on 2026-05-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contact_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['contact', '-created_at'], name='home_contac_contact_ed114a_idx'),
        ),
    ]
