# Generated by Django 4.2.30 on 2026-06-30 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_contactmessage_home_contac_contact_ed114a_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatWeDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(default='What We Do', help_text='Section title', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Short subtitle/tagline', max_length=300)),
                ('description', models.TextField(help_text='Brief description about what the company does')),
                ('services', models.JSONField(blank=True, default=list, help_text='List of {icon, title, description}')),
                ('slider_images', models.JSONField(blank=True, default=list, help_text='List of image URLs for the slider')),
                ('cta_text', models.CharField(blank=True, default='Learn More', help_text='Button text', max_length=50)),
                ('cta_link', models.CharField(blank=True, default='/services', help_text='Button link', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Order on page')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'What We Do Section',
                'verbose_name_plural': 'What We Do Sections',
                'ordering': ['order'],
            },
        ),
    ]
