# Generated by Django 4.2.30 on 2026-07-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_whatwedo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatwedo',
            name='slider_images',
            field=models.JSONField(blank=True, default=list, help_text='List of images for the slider. The FIRST entry is the main/background image; the rest are "related" images shown with their own caption. Each entry can be either a plain URL string (no caption) or an object: {"image": "<url>", "title": "...", "caption": "..."}.'),
        ),
    ]
