# Generated by Django 4.2.30 on 2026-07-02 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_alter_whatwedo_slider_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatwedo',
            name='slider_images',
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='image',
            field=models.ImageField(blank=True, help_text="Main/background image for this section's whole turn", null=True, upload_to='whatwedo/'),
        ),
        migrations.CreateModel(
            name='WhatWeDoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='whatwedo/related/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('what_we_do', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_images', to='home.whatwedo')),
            ],
            options={
                'verbose_name': 'What We Do Related Image',
                'verbose_name_plural': 'What We Do Related Images',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
