# Generated by Django 4.2.30 on 2026-07-02 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0009_remove_whatwedo_slider_images_whatwedo_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatwedo',
            name='services',
        ),
        migrations.CreateModel(
            name='WhatWeDoService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('icon', models.CharField(blank=True, help_text='Icon shortcode, e.g. :wheat:', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('what_we_do', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='home.whatwedo')),
            ],
            options={
                'verbose_name': 'What We Do Service',
                'verbose_name_plural': 'What We Do Services',
                'ordering': ['order', 'id'],
            },
        ),
    ]
