# Generated by Django 4.2.30 on 2026-07-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_whatwedo_services_whatwedoservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='description_zh',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='mission_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='mission_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='mission_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='mission_zh',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='title_ar',
            field=models.CharField(default='About Us', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='title_fr',
            field=models.CharField(default='About Us', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='title_ru',
            field=models.CharField(default='About Us', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='title_zh',
            field=models.CharField(default='About Us', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='vision_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='vision_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='vision_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='vision_zh',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_zh',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ar',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_fr',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_zh',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='cta_second_text_ar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='cta_second_text_fr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='cta_second_text_ru',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='cta_second_text_zh',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='cta_text_ar',
            field=models.CharField(default='Get Started', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='cta_text_fr',
            field=models.CharField(default='Get Started', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='cta_text_ru',
            field=models.CharField(default='Get Started', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='cta_text_zh',
            field=models.CharField(default='Get Started', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='subtitle_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='subtitle_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='subtitle_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='subtitle_zh',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title_zh',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_zh',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='name_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='name_zh',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seodata',
            name='keywords_ar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='seodata',
            name='keywords_fr',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='seodata',
            name='keywords_ru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='seodata',
            name='keywords_zh',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='seodata',
            name='meta_description_ar',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='seodata',
            name='meta_description_fr',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='seodata',
            name='meta_description_ru',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='seodata',
            name='meta_description_zh',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='seodata',
            name='meta_title_ar',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='seodata',
            name='meta_title_fr',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='seodata',
            name='meta_title_ru',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='seodata',
            name='meta_title_zh',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='servicehighlight',
            name='badge_text_ar',
            field=models.CharField(blank=True, help_text='e.g., Popular, New, Best Seller', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicehighlight',
            name='badge_text_fr',
            field=models.CharField(blank=True, help_text='e.g., Popular, New, Best Seller', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicehighlight',
            name='badge_text_ru',
            field=models.CharField(blank=True, help_text='e.g., Popular, New, Best Seller', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicehighlight',
            name='badge_text_zh',
            field=models.CharField(blank=True, help_text='e.g., Popular, New, Best Seller', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicehighlight',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='servicehighlight',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='servicehighlight',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='servicehighlight',
            name='description_zh',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='servicehighlight',
            name='title_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='servicehighlight',
            name='title_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='servicehighlight',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='servicehighlight',
            name='title_zh',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_about_text_ar',
            field=models.TextField(blank=True, help_text='About text in footer', null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_about_text_fr',
            field=models.TextField(blank=True, help_text='About text in footer', null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_about_text_ru',
            field=models.TextField(blank=True, help_text='About text in footer', null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_about_text_zh',
            field=models.TextField(blank=True, help_text='About text in footer', null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_copyright_text_ar',
            field=models.CharField(default='(c) 2025 Fee-Vert Solution Limited. All rights reserved.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_copyright_text_fr',
            field=models.CharField(default='(c) 2025 Fee-Vert Solution Limited. All rights reserved.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_copyright_text_ru',
            field=models.CharField(default='(c) 2025 Fee-Vert Solution Limited. All rights reserved.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_copyright_text_zh',
            field=models.CharField(default='(c) 2025 Fee-Vert Solution Limited. All rights reserved.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_name_ar',
            field=models.CharField(default='Fee-Vert Solution Limited', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_name_fr',
            field=models.CharField(default='Fee-Vert Solution Limited', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_name_ru',
            field=models.CharField(default='Fee-Vert Solution Limited', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_name_zh',
            field=models.CharField(default='Fee-Vert Solution Limited', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_tagline_ar',
            field=models.CharField(blank=True, help_text='Short slogan or tagline', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_tagline_fr',
            field=models.CharField(blank=True, help_text='Short slogan or tagline', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_tagline_ru',
            field=models.CharField(blank=True, help_text='Short slogan or tagline', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_tagline_zh',
            field=models.CharField(blank=True, help_text='Short slogan or tagline', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='client_company_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='client_company_fr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='client_company_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='client_company_zh',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='client_name_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='client_name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='client_name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='client_name_zh',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='client_role_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='client_role_fr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='client_role_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='client_role_zh',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='content_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='content_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='content_zh',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='cta_text_ar',
            field=models.CharField(blank=True, default='Learn More', help_text='Button text', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='cta_text_en',
            field=models.CharField(blank=True, default='Learn More', help_text='Button text', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='cta_text_fr',
            field=models.CharField(blank=True, default='Learn More', help_text='Button text', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='cta_text_ru',
            field=models.CharField(blank=True, default='Learn More', help_text='Button text', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='cta_text_sw',
            field=models.CharField(blank=True, default='Learn More', help_text='Button text', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='cta_text_zh',
            field=models.CharField(blank=True, default='Learn More', help_text='Button text', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='description_ar',
            field=models.TextField(help_text='Brief description about what the company does', null=True),
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='description_en',
            field=models.TextField(help_text='Brief description about what the company does', null=True),
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='description_fr',
            field=models.TextField(help_text='Brief description about what the company does', null=True),
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='description_ru',
            field=models.TextField(help_text='Brief description about what the company does', null=True),
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='description_sw',
            field=models.TextField(help_text='Brief description about what the company does', null=True),
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='description_zh',
            field=models.TextField(help_text='Brief description about what the company does', null=True),
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='subtitle_ar',
            field=models.CharField(blank=True, help_text='Short subtitle/tagline', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='subtitle_en',
            field=models.CharField(blank=True, help_text='Short subtitle/tagline', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='subtitle_fr',
            field=models.CharField(blank=True, help_text='Short subtitle/tagline', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='subtitle_ru',
            field=models.CharField(blank=True, help_text='Short subtitle/tagline', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='subtitle_sw',
            field=models.CharField(blank=True, help_text='Short subtitle/tagline', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='subtitle_zh',
            field=models.CharField(blank=True, help_text='Short subtitle/tagline', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='title_ar',
            field=models.CharField(default='What We Do', help_text='Section title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='title_en',
            field=models.CharField(default='What We Do', help_text='Section title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='title_fr',
            field=models.CharField(default='What We Do', help_text='Section title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='title_ru',
            field=models.CharField(default='What We Do', help_text='Section title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='title_sw',
            field=models.CharField(default='What We Do', help_text='Section title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='title_zh',
            field=models.CharField(default='What We Do', help_text='Section title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='whatwedoimage',
            name='caption_ar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='whatwedoimage',
            name='caption_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='whatwedoimage',
            name='caption_fr',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='whatwedoimage',
            name='caption_ru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='whatwedoimage',
            name='caption_sw',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='whatwedoimage',
            name='caption_zh',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='whatwedoimage',
            name='title_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='whatwedoimage',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='whatwedoimage',
            name='title_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='whatwedoimage',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='whatwedoimage',
            name='title_sw',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='whatwedoimage',
            name='title_zh',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='whatwedoservice',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatwedoservice',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatwedoservice',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatwedoservice',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatwedoservice',
            name='description_sw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatwedoservice',
            name='description_zh',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatwedoservice',
            name='title_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='whatwedoservice',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='whatwedoservice',
            name='title_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='whatwedoservice',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='whatwedoservice',
            name='title_sw',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='whatwedoservice',
            name='title_zh',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
