# Generated by Django 4.2.30 on 2026-05-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_gallery_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('honey', '🍯 Honey'), ('beeswax', '🕯️ Beeswax Products'), ('propolis', '💊 Propolis'), ('royal_jelly', '✨ Royal Jelly'), ('bee_venom', '💉 Bee Venom'), ('beehives', '🏠 Beehives'), ('equipment', '🛠️ Beekeeping Equipment'), ('bee_colonies', '🐝 Bee Colonies & Queens'), ('books', '📚 Books & Manuals'), ('other', '📦 Other')], default='other', max_length=20),
        ),
    ]
