# Generated by Django 4.2.30 on 2026-08-08 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0007_consultationrequest_category_and_more'),
        ('bookings', '0003_booking_admin_notes_ar_booking_admin_notes_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='consultations.consultationcategory'),
        ),
    ]
