# Generated by Django 5.2.1 on 2026-04-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='body_html_en',
            field=models.TextField(blank=True, help_text='HTML version for email', null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='body_html_sw',
            field=models.TextField(blank=True, help_text='HTML version for email', null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='body_text_en',
            field=models.TextField(help_text='Plain text version for SMS/In-app', null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='body_text_sw',
            field=models.TextField(help_text='Plain text version for SMS/In-app', null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='subject_en',
            field=models.CharField(help_text='Email subject or notification title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='subject_sw',
            field=models.CharField(help_text='Email subject or notification title', max_length=200, null=True),
        ),
    ]
