# Generated by Django 4.2.30 on 2026-06-22 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_contactmessage_home_contac_contact_ed114a_idx'),
        ('notifications', '0002_notificationtemplate_body_html_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sender', models.EmailField(max_length=254)),
                ('sender_name', models.CharField(blank=True, max_length=300)),
                ('recipient', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('message_id', models.CharField(max_length=500, unique=True)),
                ('thread_id', models.CharField(blank=True, max_length=500)),
                ('in_reply_to', models.CharField(blank=True, max_length=500)),
                ('received_at', models.DateTimeField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_processed', models.BooleanField(default=False)),
                ('has_attachments', models.BooleanField(default=False)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(default='outlook', max_length=50)),
                ('folder', models.CharField(default='inbox', max_length=100)),
            ],
            options={
                'verbose_name': 'Incoming Email',
                'verbose_name_plural': 'Incoming Emails',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='notificationtemplate',
            options={'ordering': ['notification_type', 'name']},
        ),
        migrations.AlterModelOptions(
            name='usernotificationsetting',
            options={'verbose_name': 'User Notification Setting', 'verbose_name_plural': 'User Notification Settings'},
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_recipie_a972ce_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_notific_47968a_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_schedul_cf7340_idx',
        ),
        migrations.RemoveIndex(
            model_name='notificationlog',
            name='notificatio_status_a242db_idx',
        ),
        migrations.RemoveIndex(
            model_name='notificationlog',
            name='notificatio_notific_a8e384_idx',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='sent_at',
            new_name='read_at',
        ),
        migrations.RenameField(
            model_name='usernotificationsetting',
            old_name='email_booking_confirmation',
            new_name='push_enabled',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_object_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_object_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='retry_count',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='scheduled_for',
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='provider_response',
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='sent_at',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='body_html',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='body_html_en',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='body_html_sw',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='body_text',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='body_text_en',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='body_text_sw',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='category',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='subject_en',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='subject_sw',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='variables',
        ),
        migrations.RemoveField(
            model_name='usernotificationsetting',
            name='email_booking_reminder',
        ),
        migrations.RemoveField(
            model_name='usernotificationsetting',
            name='email_consultation_update',
        ),
        migrations.RemoveField(
            model_name='usernotificationsetting',
            name='email_payment_receipt',
        ),
        migrations.RemoveField(
            model_name='usernotificationsetting',
            name='email_promotional',
        ),
        migrations.RemoveField(
            model_name='usernotificationsetting',
            name='in_app_all',
        ),
        migrations.RemoveField(
            model_name='usernotificationsetting',
            name='quiet_hours_end',
        ),
        migrations.RemoveField(
            model_name='usernotificationsetting',
            name='quiet_hours_start',
        ),
        migrations.RemoveField(
            model_name='usernotificationsetting',
            name='sms_booking_confirmation',
        ),
        migrations.RemoveField(
            model_name='usernotificationsetting',
            name='sms_booking_reminder',
        ),
        migrations.RemoveField(
            model_name='usernotificationsetting',
            name='sms_consultation_update',
        ),
        migrations.AddField(
            model_name='notification',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='channel',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='body_template',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='body_template_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='body_template_sw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('booking', 'Booking'), ('consultation', 'Consultation'), ('payment', 'Payment'), ('system', 'System'), ('chat', 'Chat'), ('contact', 'Contact')], default='system', max_length=50),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='subject_template',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='subject_template_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='subject_template_sw',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('booking', 'Booking'), ('consultation', 'Consultation'), ('payment', 'Payment'), ('system', 'System'), ('chat', 'Chat'), ('contact', 'Contact')], default='system', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.notification'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='usernotificationsetting',
            name='sms_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['-created_at'], name='notificatio_created_ae6ed6_idx'),
        ),
        migrations.AddField(
            model_name='incomingemail',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incomingemail',
            name='linked_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_source', to='home.contactmessage'),
        ),
        migrations.AddField(
            model_name='incomingemail',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='incomingemail',
            index=models.Index(fields=['sender'], name='notificatio_sender_8f00a2_idx'),
        ),
        migrations.AddIndex(
            model_name='incomingemail',
            index=models.Index(fields=['message_id'], name='notificatio_message_6a7c87_idx'),
        ),
        migrations.AddIndex(
            model_name='incomingemail',
            index=models.Index(fields=['thread_id'], name='notificatio_thread__aa8a10_idx'),
        ),
        migrations.AddIndex(
            model_name='incomingemail',
            index=models.Index(fields=['is_read', '-received_at'], name='notificatio_is_read_5817be_idx'),
        ),
        migrations.AddIndex(
            model_name='incomingemail',
            index=models.Index(fields=['is_processed'], name='notificatio_is_proc_432078_idx'),
        ),
    ]
