# Generated by Django 4.2.30 on 2026-07-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_incomingemail_alter_notificationtemplate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='body_template_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='body_template_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='body_template_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='body_template_zh',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='subject_template_ar',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='subject_template_fr',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='subject_template_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='subject_template_zh',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
