# Generated by Django 4.2.30 on 2026-07-03 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0004_notificationtemplate_body_template_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('provider', models.CharField(choices=[('imap', 'IMAP'), ('outlook', 'Outlook / Microsoft 365')], default='imap', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('imap_host', models.CharField(blank=True, max_length=255)),
                ('imap_port', models.IntegerField(default=993)),
                ('imap_use_ssl', models.BooleanField(default=True)),
                ('imap_password_encrypted', models.TextField(blank=True)),
                ('smtp_host', models.CharField(blank=True, max_length=255)),
                ('smtp_port', models.IntegerField(default=465)),
                ('smtp_use_ssl', models.BooleanField(default=True)),
                ('smtp_use_tls', models.BooleanField(default=False)),
                ('smtp_password_encrypted', models.TextField(blank=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_error', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('owner_user', models.ForeignKey(blank=True, help_text='Leave blank for a shared inbox visible to all staff', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_accounts', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['email_address'],
            },
        ),
        migrations.AddField(
            model_name='incomingemail',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Which mailbox this email arrived at', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_emails', to='notifications.emailaccount'),
        ),
    ]
