# Generated by Django 4.2.30 on 2026-08-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_emailaccount_incomingemail_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='is_shared',
            field=models.BooleanField(default=False, help_text='Visible to all staff (team inbox). Leave off for personal mailboxes.'),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='provider',
            field=models.CharField(choices=[('imap', 'IMAP'), ('outlook', 'Outlook / Microsoft 365'), ('zoho_api', 'Zoho Mail (API)')], default='imap', max_length=20),
        ),
    ]
