# Generated by Django 4.2.30 on 2026-08-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_emailaccount_is_shared_alter_emailaccount_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='oauth_refresh_token',
            field=models.TextField(blank=True),
        ),
    ]
