# Generated by Django 4.2.30 on 2026-08-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_emailaccount_oauth_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='oauth_client_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='oauth_client_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
