# Generated by Django 4.2.30 on 2026-08-11 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0008_emailaccount_oauth_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingemail',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Staff member handling this conversation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_emails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incomingemail',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incomingemail',
            name='snoozed_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incomingemail',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
