# Generated by Django 4.2.30 on 2026-08-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_incomingemail_assigned_to_incomingemail_is_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='aliases',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
