# Generated by Django 4.2.30 on 2026-08-14 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0010_emailaccount_aliases'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutgoingEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('from_address', models.EmailField(blank=True, max_length=254)),
                ('to_email', models.TextField(help_text='Comma-separated recipients')),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('opened', 'Opened'), ('failed', 'Failed — will retry'), ('gave_up', 'Failed — needs attention')], default='queued', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('tracking_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('open_count', models.PositiveIntegerField(default=0)),
                ('last_opened_ip', models.CharField(blank=True, max_length=64)),
                ('account', models.ForeignKey(blank=True, help_text='Mailbox this was sent from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_emails', to='notifications.emailaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('reply_to_email', models.ForeignKey(blank=True, help_text='The message this was a reply to, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='notifications.incomingemail')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Outgoing Email',
                'verbose_name_plural': 'Outgoing Emails',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'next_retry_at'], name='notificatio_status_4e9f2f_idx'), models.Index(fields=['-created_at'], name='notificatio_created_244aea_idx'), models.Index(fields=['tracking_id'], name='notificatio_trackin_19828a_idx')],
            },
        ),
    ]
