# Generated by Django 4.2.30 on 2026-08-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_outgoingemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingemail',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
