# Generated by Django 4.2.30 on 2026-08-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_outgoingemail_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='last_deep_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
